### ISSUE TITLE
Empty db_query() call

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal_analysis_blast#18]
Please line 847:
https://github.com/tripal/tripal_analysis_blast/blob/7.x-3.x/includes/TripalImporter/BlastImporter.inc#L847

I am not sure what the query is trying to retrieve so I can't determine a fix.

Thanks!

**Comment by spficklin** [comment]
Okay, I applied a fix. It was a very silly mistake of forgetting the query and args to the db_query function.  If you have additional issues pleas re-open.
