### ISSUE TITLE
change default branch to 7.x-3.x

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_blast#20]
minor suggestion.  This repo clones as  7.x-2.x.

**Comment by almasaeed2010** [comment]
Maybe we should also issue a release on the drupal repo since 2.x is there

**Comment by bradfordcondon** [comment]
yes thats definitely a good idea.  i havent checked the instructions but if they say to install from drush instead of git then its a necessity.

**Comment by spficklin** [comment]
Default branch has been set to 7.x-3.x.   We should issue a 3.x release, but we need to make sure all is okay.  Are you using the module in production?

**Comment by almasaeed2010** [comment]
We are using it in production but I’d like #26 to be fixed first if possible.

Thanks!

**Comment by spficklin** [comment]
Is someone working on a fix for #26?

**Comment by bradfordcondon** [comment]
@almasaeed2010 offered but i wanted to wait for approval from someoen else about not drawing the blank diagram.  

Abdullah are you able to make the PR or would you like me to?

**Comment by almasaeed2010** [comment]
Yes I can get it done 👍

**Comment by spficklin** [comment]
I'm closing this out as it's not really an issue.
