### ISSUE TITLE
NCBI NR parser

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_blast#21]
this issue was spawned from https://github.com/tripal/tripal/issues/284 originally created by @btski

![image](https://user-images.githubusercontent.com/7063154/40783569-dfd58426-64b0-11e8-95ff-972276141e6c.png)

>However, I see your point that it does look a bit odd. I think what you're suggesting is that you would have expected the hit name to just be the accession (e.g. XP_002302784.1) and the hit description to be the full text. Is this right?

but note @mpoelchau 's comment:  

>  my main concern would be that the GenBank defline format (and RefSeq) seems to have changed since NCBI deprecated GI numbers.
> 
> https://ncbi.github.io/cxx-toolkit/pages/ch_demo#ch_demo.T5
> 
> GenBank fasta defline format now seems to be gb|accession|locus instead of gi|GInumber|gb|accession

**Comment by spficklin** [comment]
I have added a fix for this.  I committed it to the open PR #29 because there are some major changes there that this fix relies on.  In short. I swapped out the accession for the hit_id.

**Comment by almasaeed2010** [comment]
Merged! Thanks!
