### ISSUE TITLE
Usage doc

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal_analysis_blast#25]
Hi,
Now the 3.x module installs fine in our docker image, and I can load data with python-tripal and python-chado.
I'm just wondering what I'm supposed to do to display the blast results for the mRNA entities. Is it a field I should manually add to it (I couldn't find it in the list)? Do I need to publish blast results somehow?

**Comment by bradfordcondon** [comment]
hi @abretaud first of all apologies, these docs are actively in the works.

Once hte module is enabled, you can go to the content type settings (structure -> tripal content ->[content type]) the field will attach to (in your case mRNA). Press the "check for new fields" button- you should get a `format__blast_results` field attached.  Next, click on "display" and set this field to enabled for it to show up (fields attach without being displayed by default).

**Comment by abretaud** [comment]
Thanks, it worked!
