### ISSUE TITLE
View is munged when blast results added

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal_analysis_blast#36]
When the blast module is enabled the following happens to the view on the demo site:

![blast](https://user-images.githubusercontent.com/1719352/56777043-1f4d1480-6784-11e9-8134-8611fae7fae9.png)
If the blast panel is removed then all is corrected.

**Comment by almasaeed2010** [comment]
I can confirm this issue happens when the field is added to any pane other than summary. Looks like a basic HTML error.

<img width="766" alt="Screen Shot 2019-04-26 at 8 07 04 AM" src="https://user-images.githubusercontent.com/1512664/56806576-4cd4a500-67fa-11e9-868e-a44204e12307.png">

**Comment by almasaeed2010** [comment]
Fixed in #37
