### ISSUE TITLE
When tripal_ds is enabled field doesn't show alignment bars

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal_analysis_blast#8]

**Comment by kyrenya** [comment]
hi there, same issue here: 

![image](https://user-images.githubusercontent.com/43243429/49590088-dc200f80-f962-11e8-8e9b-fffb7407aa25.png)

When I disable tripal_ds,  I see the blue lines, but just that. 

![image](https://user-images.githubusercontent.com/43243429/49590225-3b7e1f80-f963-11e8-84be-1cf23ba86ad0.png)

and because of tripal_ds disabled, weird things in other fields like gene ones, where there is no tripal panes navigation menu anymore.
![image](https://user-images.githubusercontent.com/43243429/49590252-4fc21c80-f963-11e8-85ee-32fe03244012.png)

any help? Thanks!

**Comment by spficklin** [comment]
Yes, the tripal_ds module provides some really handy out-of-the-box organization of fields.  But some folks who prefer to do layouts on their own will turn it off and organize the fields as they want.   If you're not used to it it will make things look a mess at first.  We can knock up the priority to try and fix this.

**Comment by kyrenya** [comment]
ok, thx! I've also checked, and I have the same problem with interpro results visualization. Changing browser changes a bit what I see, but still doesnt display properly. maybe this info helps you. 
Thanks, cheers!

**Comment by spficklin** [comment]
@kyrenya I want to try and resolve this problem and I discovered I am not experiencing this any longer. Here's my results page:

![image](https://user-images.githubusercontent.com/1719352/49679439-2cb96a80-fa40-11e8-865e-7c24653a1848.png)

So, to try and resolve what's going on at your end.
1.  Are you using the development branch (7.x-3.x) of this module?
2.  Do you have the jquery_update module installed.  I currently have mine set to JQuery 1.9 (Admin > Configure > Jquery Update)

**Comment by kyrenya** [comment]
hi! sorry for my late answer, I realised I had another issue about replicate entries, and then I left this issue in standby.  But I answer you: 
1. Nop, I didnt have the dev version, but the branch (7.x-3.x)

![image](https://user-images.githubusercontent.com/43243429/49817134-60113780-fd67-11e8-958f-10cf4ae2854a.png)

2. my Jquery_update module right now is in this situation: 
![image](https://user-images.githubusercontent.com/43243429/49817380-f47b9a00-fd67-11e8-948f-e32ac5c95aae.png)


Shall I change to 1.9 for both version options? (**Default jQuery Version** and **Alternate jQuery version for administrative pages**)

**Comment by spficklin** [comment]
Okay, so the dev version is the same as branch 7.x-3.x.  If you're on that branch and you have pulled it recently then we're using the same code.

I do vaguely recall an issue with JQuery at version 1.10.  But I don't remember.  Can you try switching it to 1.9  and see?

**Comment by kyrenya** [comment]
Sure! I will let you know as soon as I have the data ready to try it! Thx for your answer! :)

**Comment by kyrenya** [comment]
Hi, Came back to this now.. 
This is what I see. 
![image](https://user-images.githubusercontent.com/43243429/50342132-b7f32f80-0519-11e9-9caa-f315316c5c58.png)



I already changed the JQuery version to 1.9

Any ideas?

**Comment by kyrenya** [comment]
I noticed two things: 
1. If I choose the option Load field using AJAX (in MRNA field), BLAST results field disappear.
2. Only if in managing display of the field mRNA I click in Full Content instead of Teaser (Custom display settings), I can see then tthe alignments... 
does this help?

**Comment by spficklin** [comment]
Hi @kyrenya.  That was helpful.  Thank you.  I believe I have tracked down the problem.  I have applied a fix to a new branch of the code named `8-tv3-missing_viewer`.  Can you pull that branch, clear your cache and try viewing the results again?   

```
git checkout 8-tv3-missing_viewer
drush cc all
```

There is one case where it still won't work.  This is when you first load the page after clearing the cache (or clicking the 'Reload' tab at the top of the page).  Any subsequent loading of the page thereafter should work just fine.  To fix the first load problem I think we'll need a fix at the Tripal end.

**Comment by spficklin** [comment]
Hi @kyrenya.  Since the AJAX issue may not get resolved quickly, I altered the field so that it is "auto attached" meaning even if AJAX is enabled, the blast field will not be loaded via AJAX.   This gets around the AJAX issue until we can fix the issue with Tripal core.  I've made the fix to the same branch.  Also, I altered the layout of the results a bit because it can get extremely long.  It now uses an accordion so you'll see that change as well.   To get the fix for the AJAX you'll have to run a `drush updatedb` after you pull the branch and clear the cache.

**Comment by spficklin** [comment]
@kyrenya one last detail I forgot to include.  The fix that I describe in two comments above this one requires a fix to the Tripal core as well.  I have made that fix and submitted it for review. It is PR https://github.com/tripal/tripal/pull/806. Once the code changes in that PR are approved and merged in then you would need to update Tripal and then you can perform the tests I mention above.  

So, you might just want to wait until that gets merged..

**Comment by kyrenya** [comment]
Cool! Ok Ill do that! Thanks a lot for taking care of this! Ill keep you posted once I try it. Happy new year!

**Comment by almasaeed2010** [comment]
This appears to be fixed? If you still have issues @kyrenya, please feel free to reopen the issue!

Thanks!
